-- 00-schema-setup.sql
--
-- Goal:
--   Create the common teaching schema objects used by the PL/SQL examples.
--
-- Objects:
--   COURSE_STUDENT, COURSE_STUDENT_AUDIT, COURSE_STUDENT_SEQ

SET SERVEROUTPUT ON

PROMPT Dropping old objects when they exist...

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER course_student_biu_trg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE course_student_audit PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE course_student PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE course_student_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE course_student (
    student_id NUMBER        PRIMARY KEY,
    name  VARCHAR2(100) NOT NULL,
    city       VARCHAR2(50)  NOT NULL,
    grade      NUMBER(3,1),
    note       VARCHAR2(100)
);

CREATE TABLE course_student_audit (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_ts      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    action_name   VARCHAR2(10) NOT NULL,
    student_id    NUMBER,
    old_note      VARCHAR2(100),
    new_note      VARCHAR2(100),
    changed_by    VARCHAR2(128) DEFAULT USER NOT NULL
);

CREATE SEQUENCE course_student_seq
    START WITH 100
    INCREMENT BY 1
    NOCACHE;

INSERT INTO course_student(student_id, name, city, grade, note)
VALUES (1, 'Alice', 'Praha', 1.5, 'excellent');

INSERT INTO course_student(student_id, name, city, grade, note)
VALUES (2, 'Bob', 'Brno', 2.0, NULL);

INSERT INTO course_student(student_id, name, city, grade, note)
VALUES (3, 'Tomas', 'Ostrava', NULL, 'needs topic');

INSERT INTO course_student(student_id, name, city, grade, note)
VALUES (4, 'Jana', 'Brno', 2.7, NULL);

COMMIT;

PROMPT Current data:
COLUMN name FORMAT A12
COLUMN city FORMAT A10
COLUMN note FORMAT A20

SELECT student_id, name, city, grade, note
FROM course_student
ORDER BY student_id;
