#!/usr/bin/env bash
set -euo pipefail

PDB_NAME="${EXAMPLE_PDB:-XEPDB1}"
APP_USER="${EXAMPLE_USER:-STUDENT}"
APP_PASSWORD="${EXAMPLE_USER_PASSWORD:-Student2026!}"

echo "Creating example user ${APP_USER} in PDB ${PDB_NAME} ..."

sqlplus -s / as sysdba <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
PROMPT Create new user ${APP_USER} in PDB ${PDB_NAME}.

ALTER SESSION SET CONTAINER=${PDB_NAME};

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM dba_users
     WHERE username = UPPER('${APP_USER}');

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ${APP_USER} IDENTIFIED BY "${APP_PASSWORD}"';
    END IF;
END;
/
GRANT CREATE SESSION TO ${APP_USER};
GRANT CREATE TABLE TO ${APP_USER};
GRANT CREATE TYPE TO ${APP_USER};
GRANT CREATE VIEW TO ${APP_USER};
GRANT CREATE SEQUENCE TO ${APP_USER};
GRANT CREATE PROCEDURE TO ${APP_USER};
GRANT CREATE TRIGGER TO ${APP_USER};
GRANT CREATE SYNONYM TO ${APP_USER};
GRANT UNLIMITED TABLESPACE TO ${APP_USER};

EXIT
SQL
