-- 00-hello-world-demo.sql
--
-- Goal:
--   Create the common teaching schema objects used by the PL/SQL examples.
--
-- Objects:
--   ESQL_STUDENT, ESQL_STUDENT_AUDIT, ESQL_STUDENT_SEQ

PROMPT === Hello World DEMO ===

-- show output from DBMS_OUTPUT used in PL/SQL
SET SERVEROUTPUT ON
-- show SQL
SET ECHO ON
-- show output in terminal
SET TERMOUT ON
-- show number of modified rows
SET FEEDBACK ON
-- enable logging to the file
SPOOL output.log
-- displays the execution time of each SQL statement
SET TIMING ON
-- disable logging to the file
SPOOL OFF

CREATE TABLE esql_demo (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR2(100)
);

INSERT INTO esql_demo(note) VALUES ('hello from docker example');

COMMIT;

SELECT * FROM esql_demo ORDER BY id;

DROP TABLE esql_demo;

COMMIT;

