PROMPT === Hello World DEMO ===

CREATE TABLE esql_demo (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR2(100)
);

INSERT INTO esql_demo(note) VALUES ('hello from docker example');
COMMIT;

SELECT * FROM esql_demo ORDER BY id;
