-- 00-hello-world-demo.sql
--
-- Goal:
--   Hello World for Oracle Database container.
--
-- Objects:
--   KIV_DBA_STUDENT_DEMO

PROMPT === Hello World DEMO ===

-- show output from DBMS_OUTPUT used in PL/SQL
SET SERVEROUTPUT ON
-- show SQL
SET ECHO ON
-- show output in terminal
SET TERMOUT ON
-- show number of modified rows
SET FEEDBACK ON
-- enable logging to the file
SPOOL output.log
-- displays the execution time of each SQL statement
SET TIMING ON
-- disable logging to the file
SPOOL OFF

CREATE TABLE kiv_dba_student_demo (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR2(100)
);

INSERT INTO kiv_dba_student_demo(note) VALUES ('hello from docker example');

COMMIT;

SELECT * FROM kiv_dba_student_demo ORDER BY id;

DROP TABLE kiv_dba_student_demo;

COMMIT;

